package com.sforce.apex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Manage your Salesforce.com Apex classes and triggers
 *
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-21T07:44:17.168-05:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "ApexService",
                  wsdlLocation = "file:/D:/Elan/virtualan-working-dir/service-vir/virtualan/samples/virtualan-wsdl-soap/src/main/resources/META-INF/resources/wsdl/Salesforce-49/apex.wsdl",
                  targetNamespace = "http://soap.sforce.com/2006/08/apex")
public class ApexService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.sforce.com/2006/08/apex", "ApexService");
    public final static QName Apex = new QName("http://soap.sforce.com/2006/08/apex", "Apex");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Elan/virtualan-working-dir/service-vir/virtualan/samples/virtualan-wsdl-soap/src/main/resources/META-INF/resources/wsdl/Salesforce-49/apex.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ApexService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Elan/virtualan-working-dir/service-vir/virtualan/samples/virtualan-wsdl-soap/src/main/resources/META-INF/resources/wsdl/Salesforce-49/apex.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ApexService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ApexService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApexService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ApexService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ApexService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ApexService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ApexPortType
     */
    @WebEndpoint(name = "Apex")
    public ApexPortType getApex() {
        return super.getPort(Apex, ApexPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApexPortType
     */
    @WebEndpoint(name = "Apex")
    public ApexPortType getApex(WebServiceFeature... features) {
        return super.getPort(Apex, ApexPortType.class, features);
    }

}
