
package com.sforce.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-21T07:44:16.975-05:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "InvalidOldPasswordFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class InvalidOldPasswordFault_Exception extends Exception {

    private com.sforce.partner.InvalidOldPasswordFault invalidOldPasswordFault;

    public InvalidOldPasswordFault_Exception() {
        super();
    }

    public InvalidOldPasswordFault_Exception(String message) {
        super(message);
    }

    public InvalidOldPasswordFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidOldPasswordFault_Exception(String message, com.sforce.partner.InvalidOldPasswordFault invalidOldPasswordFault) {
        super(message);
        this.invalidOldPasswordFault = invalidOldPasswordFault;
    }

    public InvalidOldPasswordFault_Exception(String message, com.sforce.partner.InvalidOldPasswordFault invalidOldPasswordFault, java.lang.Throwable cause) {
        super(message, cause);
        this.invalidOldPasswordFault = invalidOldPasswordFault;
    }

    public com.sforce.partner.InvalidOldPasswordFault getFaultInfo() {
        return this.invalidOldPasswordFault;
    }
}
