
package com.sforce.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-21T07:44:16.955-05:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "InvalidQueryLocatorFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class InvalidQueryLocatorFault_Exception extends Exception {

    private com.sforce.partner.InvalidQueryLocatorFault invalidQueryLocatorFault;

    public InvalidQueryLocatorFault_Exception() {
        super();
    }

    public InvalidQueryLocatorFault_Exception(String message) {
        super(message);
    }

    public InvalidQueryLocatorFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidQueryLocatorFault_Exception(String message, com.sforce.partner.InvalidQueryLocatorFault invalidQueryLocatorFault) {
        super(message);
        this.invalidQueryLocatorFault = invalidQueryLocatorFault;
    }

    public InvalidQueryLocatorFault_Exception(String message, com.sforce.partner.InvalidQueryLocatorFault invalidQueryLocatorFault, java.lang.Throwable cause) {
        super(message, cause);
        this.invalidQueryLocatorFault = invalidQueryLocatorFault;
    }

    public com.sforce.partner.InvalidQueryLocatorFault getFaultInfo() {
        return this.invalidQueryLocatorFault;
    }
}
