
package com.sforce.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-21T07:44:16.943-05:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "InvalidSObjectFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class InvalidSObjectFault_Exception extends Exception {

    private com.sforce.partner.InvalidSObjectFault invalidSObjectFault;

    public InvalidSObjectFault_Exception() {
        super();
    }

    public InvalidSObjectFault_Exception(String message) {
        super(message);
    }

    public InvalidSObjectFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidSObjectFault_Exception(String message, com.sforce.partner.InvalidSObjectFault invalidSObjectFault) {
        super(message);
        this.invalidSObjectFault = invalidSObjectFault;
    }

    public InvalidSObjectFault_Exception(String message, com.sforce.partner.InvalidSObjectFault invalidSObjectFault, java.lang.Throwable cause) {
        super(message, cause);
        this.invalidSObjectFault = invalidSObjectFault;
    }

    public com.sforce.partner.InvalidSObjectFault getFaultInfo() {
        return this.invalidSObjectFault;
    }
}
