
package com.sforce.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-21T07:44:16.958-05:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "InvalidIdFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class InvalidIdFault_Exception extends Exception {

    private com.sforce.partner.InvalidIdFault invalidIdFault;

    public InvalidIdFault_Exception() {
        super();
    }

    public InvalidIdFault_Exception(String message) {
        super(message);
    }

    public InvalidIdFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidIdFault_Exception(String message, com.sforce.partner.InvalidIdFault invalidIdFault) {
        super(message);
        this.invalidIdFault = invalidIdFault;
    }

    public InvalidIdFault_Exception(String message, com.sforce.partner.InvalidIdFault invalidIdFault, java.lang.Throwable cause) {
        super(message, cause);
        this.invalidIdFault = invalidIdFault;
    }

    public com.sforce.partner.InvalidIdFault getFaultInfo() {
        return this.invalidIdFault;
    }
}
