
package com.sforce.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-21T07:44:16.967-05:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "LoginFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class LoginFault_Exception extends Exception {

    private com.sforce.partner.LoginFault loginFault;

    public LoginFault_Exception() {
        super();
    }

    public LoginFault_Exception(String message) {
        super(message);
    }

    public LoginFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public LoginFault_Exception(String message, com.sforce.partner.LoginFault loginFault) {
        super(message);
        this.loginFault = loginFault;
    }

    public LoginFault_Exception(String message, com.sforce.partner.LoginFault loginFault, java.lang.Throwable cause) {
        super(message, cause);
        this.loginFault = loginFault;
    }

    public com.sforce.partner.LoginFault getFaultInfo() {
        return this.loginFault;
    }
}
