
package com.sforce.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-21T07:44:16.951-05:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "MalformedQueryFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class MalformedQueryFault_Exception extends Exception {

    private com.sforce.partner.MalformedQueryFault malformedQueryFault;

    public MalformedQueryFault_Exception() {
        super();
    }

    public MalformedQueryFault_Exception(String message) {
        super(message);
    }

    public MalformedQueryFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public MalformedQueryFault_Exception(String message, com.sforce.partner.MalformedQueryFault malformedQueryFault) {
        super(message);
        this.malformedQueryFault = malformedQueryFault;
    }

    public MalformedQueryFault_Exception(String message, com.sforce.partner.MalformedQueryFault malformedQueryFault, java.lang.Throwable cause) {
        super(message, cause);
        this.malformedQueryFault = malformedQueryFault;
    }

    public com.sforce.partner.MalformedQueryFault getFaultInfo() {
        return this.malformedQueryFault;
    }
}
