
package com.sforce.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-21T07:44:16.963-05:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "MalformedSearchFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class MalformedSearchFault_Exception extends Exception {

    private com.sforce.partner.MalformedSearchFault malformedSearchFault;

    public MalformedSearchFault_Exception() {
        super();
    }

    public MalformedSearchFault_Exception(String message) {
        super(message);
    }

    public MalformedSearchFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public MalformedSearchFault_Exception(String message, com.sforce.partner.MalformedSearchFault malformedSearchFault) {
        super(message);
        this.malformedSearchFault = malformedSearchFault;
    }

    public MalformedSearchFault_Exception(String message, com.sforce.partner.MalformedSearchFault malformedSearchFault, java.lang.Throwable cause) {
        super(message, cause);
        this.malformedSearchFault = malformedSearchFault;
    }

    public com.sforce.partner.MalformedSearchFault getFaultInfo() {
        return this.malformedSearchFault;
    }
}
