package com.sforce.partner;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-21T07:44:16.979-05:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "urn:partner.soap.sforce.com", name = "Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface Soap {

    /**
     * Get the next chunk of snapshot results
     */
    @WebMethod
    @RequestWrapper(localName = "moreSnapshot", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.MoreSnapshot")
    @ResponseWrapper(localName = "moreSnapshotResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.MoreSnapshotResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.SnapshotResult moreSnapshot(

        @WebParam(name = "snapshotLocator", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String snapshotLocator
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Update organization preferences
     */
    @WebMethod
    @RequestWrapper(localName = "updateSettings", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.UpdateSettings")
    @ResponseWrapper(localName = "updateSettingsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.UpdateSettingsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.SaveResult> updateSettings(

        @WebParam(name = "settingNames", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> settingNames,
        @WebParam(name = "settingValues", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> settingValues
    );

    /**
     * Merge Email using the specified template
     */
    @WebMethod
    @RequestWrapper(localName = "emailMerge", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.EmailMerge")
    @ResponseWrapper(localName = "emailMergeResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.EmailMergeResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<java.lang.String> emailMerge(

        @WebParam(name = "template", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String template,
        @WebParam(name = "id", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> id
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Find duplicates for a set of sObjects
     */
    @WebMethod
    @RequestWrapper(localName = "findDuplicates", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.FindDuplicates")
    @ResponseWrapper(localName = "findDuplicatesResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.FindDuplicatesResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.FindDuplicatesResult> findDuplicates(

        @WebParam(name = "sObjects", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.SObject> sObjects
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception, InvalidFieldFault_Exception;

    /**
     * Returns standard information relevant to the current user
     */
    @WebMethod
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.GetUserInfoResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.GetUserInfoResult getUserInfo()
 throws UnexpectedErrorFault_Exception;

    /**
     * Describe Gloal and Themes
     */
    @WebMethod
    @RequestWrapper(localName = "describeGlobalTheme", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeGlobalTheme")
    @ResponseWrapper(localName = "describeGlobalThemeResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeGlobalThemeResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeGlobalTheme2 describeGlobalTheme()
 throws UnexpectedErrorFault_Exception;

    /**
     * Describe the approval layouts of the given sObject
     */
    @WebMethod
    @RequestWrapper(localName = "describeApprovalLayout", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeApprovalLayout")
    @ResponseWrapper(localName = "describeApprovalLayoutResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeApprovalLayoutResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeApprovalLayoutResult describeApprovalLayout(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType,
        @WebParam(name = "approvalProcessNames", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> approvalProcessNames
    );

    /**
     * Gets the next batch of sObjects from a query
     */
    @WebMethod
    @RequestWrapper(localName = "queryMore", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.QueryMore")
    @ResponseWrapper(localName = "queryMoreResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.QueryMoreResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.QueryResult queryMore(

        @WebParam(name = "queryLocator", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String queryLocator
    ) throws MalformedQueryFault_Exception, UnexpectedErrorFault_Exception, InvalidFieldFault_Exception, InvalidQueryLocatorFault_Exception;

    /**
     * Describe the layout of the given sObject or the given actionable global page.
     */
    @WebMethod
    @RequestWrapper(localName = "describeLayout", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeLayout")
    @ResponseWrapper(localName = "describeLayoutResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeLayoutResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeLayoutResult describeLayout(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType,
        @WebParam(name = "layoutName", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String layoutName,
        @WebParam(name = "recordTypeIds", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> recordTypeIds
    ) throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Navigates a flow interview
     */
    @WebMethod
    @RequestWrapper(localName = "navigateFlowInterview", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.NavigateFlowInterview")
    @ResponseWrapper(localName = "navigateFlowInterviewResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.NavigateFlowInterviewResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.NavigateFlowInterviewResult navigateFlowInterview(

        @WebParam(name = "request", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.NavigateFlowInterviewRequest request
    );

    /**
     * Describe the items in an AppMenu
     */
    @WebMethod
    @RequestWrapper(localName = "describeAppMenu", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeAppMenu")
    @ResponseWrapper(localName = "describeAppMenuResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeAppMenuResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeAppMenuResult describeAppMenu(

        @WebParam(name = "appMenuType", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.AppMenuType appMenuType,
        @WebParam(name = "networkId", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String networkId
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Describe the lookup view of an sObject
     */
    @WebMethod
    @RequestWrapper(localName = "describeLookupLayouts", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeLookupLayouts")
    @ResponseWrapper(localName = "describeLookupLayoutsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeLookupLayoutsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeLookupLayoutResult> describeLookupLayouts(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> sObjectType
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Search for sObjects
     */
    @WebMethod
    @RequestWrapper(localName = "outlookSearch", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.OutlookSearch")
    @ResponseWrapper(localName = "outlookSearchResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.OutlookSearchResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.OutlookSearchResult outlookSearch(

        @WebParam(name = "searchExpr", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String searchExpr,
        @WebParam(name = "contextString", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String contextString
    ) throws MalformedSearchFault_Exception, UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception, InvalidFieldFault_Exception;

    /**
     * Login to the Salesforce.com SOAP Api
     */
    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.LoginResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.LoginResult login(

        @WebParam(name = "username", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String password
    ) throws LoginFault_Exception, InvalidIdFault_Exception, UnexpectedErrorFault_Exception;

    /**
     * Describe the compact layouts of the given sObject
     */
    @WebMethod
    @RequestWrapper(localName = "describeCompactLayouts", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeCompactLayouts")
    @ResponseWrapper(localName = "describeCompactLayoutsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeCompactLayoutsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeCompactLayoutsResult describeCompactLayouts(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType,
        @WebParam(name = "recordTypeIds", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> recordTypeIds
    );

    /**
     * Describe the ListViews as SOQL metadata for the generation of SOQL.
     */
    @WebMethod
    @RequestWrapper(localName = "describeSoqlListViews", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSoqlListViews")
    @ResponseWrapper(localName = "describeSoqlListViewsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSoqlListViewsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeSoqlListViewResult describeSoqlListViews(

        @WebParam(name = "request", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.DescribeSoqlListViewsRequest request
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Describe the Path Assistants for the given sObject and optionally RecordTypes
     */
    @WebMethod
    @RequestWrapper(localName = "describePathAssistants", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribePathAssistants")
    @ResponseWrapper(localName = "describePathAssistantsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribePathAssistantsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribePathAssistantsResult describePathAssistants(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType,
        @WebParam(name = "picklistValue", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String picklistValue,
        @WebParam(name = "recordTypeIds", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> recordTypeIds
    );

    /**
     * Get the defaults for a given sobject type
     */
    @WebMethod
    @RequestWrapper(localName = "retrieveDefaultValues", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.RetrieveDefaultValues")
    @ResponseWrapper(localName = "retrieveDefaultValuesResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.RetrieveDefaultValuesResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.SObject retrieveDefaultValues(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType,
        @WebParam(name = "recordTypeId", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String recordTypeId,
        @WebParam(name = "fieldList", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String fieldList
    ) throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Login as a different user name across instances
     */
    @WebMethod
    @RequestWrapper(localName = "loginXi", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.LoginXi")
    @ResponseWrapper(localName = "loginXiResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.LoginXiResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.LoginResult loginXi(

        @WebParam(name = "username", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String username
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Mega describe with mobile specific info
     */
    @WebMethod
    @RequestWrapper(localName = "describeMobile", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeMobile")
    @ResponseWrapper(localName = "describeMobileResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeMobileResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeMobileResult describeMobile()
 throws UnexpectedErrorFault_Exception;

    /**
     * initialize briefcase
     */
    @WebMethod
    @RequestWrapper(localName = "setupBriefcase", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.SetupBriefcase")
    @ResponseWrapper(localName = "setupBriefcaseResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.SetupBriefcaseResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.SetupBriefcaseResult setupBriefcase()
 throws UnexpectedErrorFault_Exception;

    /**
     * Transport events(Page views, CUD on objects, Listview runs etc) from Lightning and capture using the Event Monitoring framework.
     */
    @WebMethod
    @RequestWrapper(localName = "captureCommonEvent", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.CaptureCommonEvent")
    @ResponseWrapper(localName = "captureCommonEventResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.CaptureCommonEventResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.CommonEventResult captureCommonEvent(

        @WebParam(name = "appName", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String appName,
        @WebParam(name = "eventValues", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String eventValues,
        @WebParam(name = "eventName", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.EventName eventName
    );

    /**
     * Describe the layout of the given sObject or the given actionable global page.
     */
    @WebMethod
    @RequestWrapper(localName = "describeLayoutByUiType", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeLayoutByUiType")
    @ResponseWrapper(localName = "describeLayoutByUiTypeResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeLayoutByUiTypeResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeLayoutResult describeLayoutByUiType(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType,
        @WebParam(name = "layoutName", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String layoutName,
        @WebParam(name = "recordTypeIds", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> recordTypeIds,
        @WebParam(name = "uiType", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.UiType uiType
    ) throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Describe the tabs that appear on a users page
     */
    @WebMethod
    @RequestWrapper(localName = "describeTabs", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeTabs")
    @ResponseWrapper(localName = "describeTabsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeTabsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeTabSetResult> describeTabs()
 throws UnexpectedErrorFault_Exception;

    /**
     * Search for sObjects
     */
    @WebMethod
    @RequestWrapper(localName = "search", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.SearchResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.SearchResult search(

        @WebParam(name = "searchString", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String searchString
    ) throws MalformedSearchFault_Exception, UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception, InvalidFieldFault_Exception;

    /**
     * Get the IDs for updated sObjects
     */
    @WebMethod
    @RequestWrapper(localName = "getUpdated", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.GetUpdated")
    @ResponseWrapper(localName = "getUpdatedResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.GetUpdatedResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.GetUpdatedResult getUpdated(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType,
        @WebParam(name = "startDate", targetNamespace = "urn:partner.soap.sforce.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "urn:partner.soap.sforce.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Describe Outlook Plugin-specific information
     */
    @WebMethod
    @RequestWrapper(localName = "outlookDescribe", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.OutlookDescribe")
    @ResponseWrapper(localName = "outlookDescribeResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.OutlookDescribeResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.OutlookDescribeResult outlookDescribe()
 throws UnexpectedErrorFault_Exception;

    /**
     * Describe the details of a series of quick actions in context of requested recordType id for Update actions
     */
    @WebMethod
    @RequestWrapper(localName = "describeQuickActionsForRecordType", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeQuickActionsForRecordType")
    @ResponseWrapper(localName = "describeQuickActionsForRecordTypeResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeQuickActionsForRecordTypeResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeQuickActionResult> describeQuickActionsForRecordType(

        @WebParam(name = "quickActions", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> quickActions,
        @WebParam(name = "recordTypeId", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String recordTypeId
    );

    /**
     * Returns generated jwt token
     */
    @WebMethod
    @RequestWrapper(localName = "generateJwtToken", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.GenerateJwtToken")
    @ResponseWrapper(localName = "generateJwtTokenResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.GenerateJwtTokenResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.lang.String generateJwtToken(

        @WebParam(name = "claims", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.ClaimsMapping> claims
    );

    /**
     * Perform a template merge on one or more blocks of text.
     */
    @WebMethod
    @RequestWrapper(localName = "renderEmailTemplate", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.RenderEmailTemplate")
    @ResponseWrapper(localName = "renderEmailTemplateResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.RenderEmailTemplateResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.RenderEmailTemplateResult> renderEmailTemplate(

        @WebParam(name = "renderRequests", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.RenderEmailTemplateRequest> renderRequests
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Update or insert a set of sObjects based on object id
     */
    @WebMethod
    @RequestWrapper(localName = "upsert", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Upsert")
    @ResponseWrapper(localName = "upsertResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.UpsertResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.UpsertResult> upsert(

        @WebParam(name = "externalIDFieldName", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String externalIDFieldName,
        @WebParam(name = "sObjects", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.SObject> sObjects
    ) throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception, InvalidFieldFault_Exception;

    /**
     * Describe the details of a series of quick actions
     */
    @WebMethod
    @RequestWrapper(localName = "describeQuickActions", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeQuickActions")
    @ResponseWrapper(localName = "describeQuickActionsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeQuickActionsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeQuickActionResult> describeQuickActions(

        @WebParam(name = "quickActions", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> quickActions
    );

    /**
     * Describe multiple sObjects (upto 100)
     */
    @WebMethod
    @RequestWrapper(localName = "describeSObjects", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSObjects")
    @ResponseWrapper(localName = "describeSObjectsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSObjectsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeSObjectResult> describeSObjects(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> sObjectType
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * For testing purposes only
     */
    @WebMethod
    @RequestWrapper(localName = "ftestPatch", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.FtestPatch")
    @ResponseWrapper(localName = "ftestPatchResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.FtestPatchResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.SaveResult ftestPatch()
;

    /**
     * Describes your Knowledge settings, such as if knowledgeEnabled is on or off, its default language and supported languages
     */
    @WebMethod
    @RequestWrapper(localName = "describeKnowledgeSettings", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeKnowledgeSettings")
    @ResponseWrapper(localName = "describeKnowledgeSettingsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeKnowledgeSettingsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.KnowledgeSettings describeKnowledgeSettings()
 throws UnexpectedErrorFault_Exception;

    /**
     * Describe the mini layout of an sObject
     */
    @WebMethod
    @RequestWrapper(localName = "describeMiniLayout", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeMiniLayout")
    @ResponseWrapper(localName = "describeMiniLayoutResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeMiniLayoutResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeMiniLayoutResult describeMiniLayout(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType,
        @WebParam(name = "layoutName", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String layoutName,
        @WebParam(name = "recordTypeIds", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> recordTypeIds
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Describe Themes
     */
    @WebMethod
    @RequestWrapper(localName = "describeTheme", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeTheme")
    @ResponseWrapper(localName = "describeThemeResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeThemeResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeThemeResult describeTheme(

        @WebParam(name = "sobjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> sobjectType
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Delete a set of sObjects by example. The passed SOBject is a template for the object to delete
     */
    @WebMethod
    @RequestWrapper(localName = "deleteByExample", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DeleteByExample")
    @ResponseWrapper(localName = "deleteByExampleResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DeleteByExampleResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DeleteByExampleResult> deleteByExample(

        @WebParam(name = "sObjects", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.SObject> sObjects
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Execute the specified list view and return the presentation-ready results.
     */
    @WebMethod
    @RequestWrapper(localName = "executeListView", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ExecuteListView")
    @ResponseWrapper(localName = "executeListViewResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ExecuteListViewResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.ExecuteListViewResult executeListView(

        @WebParam(name = "request", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.ExecuteListViewRequest request
    );

    /**
     * Perform a template merge using an email template stored in the database.
     */
    @WebMethod
    @RequestWrapper(localName = "renderStoredEmailTemplate", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.RenderStoredEmailTemplate")
    @ResponseWrapper(localName = "renderStoredEmailTemplateResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.RenderStoredEmailTemplateResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.RenderStoredEmailTemplateResult renderStoredEmailTemplate(

        @WebParam(name = "request", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.RenderStoredEmailTemplateRequest request
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Describe visualforce for an org
     */
    @WebMethod
    @RequestWrapper(localName = "describeVisualForce", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeVisualForce")
    @ResponseWrapper(localName = "describeVisualForceResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeVisualForceResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeVisualForceResult describeVisualForce(

        @WebParam(name = "includeAllDetails", targetNamespace = "urn:partner.soap.sforce.com")
        boolean includeAllDetails,
        @WebParam(name = "namespacePrefix", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String namespacePrefix
    );

    /**
     * Set a user's password
     */
    @WebMethod
    @RequestWrapper(localName = "setPassword", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.SetPassword")
    @ResponseWrapper(localName = "setPasswordResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.SetPasswordResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.SetPasswordResult setPassword(

        @WebParam(name = "userId", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String userId,
        @WebParam(name = "password", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String password
    ) throws InvalidIdFault_Exception, InvalidNewPasswordFault_Exception, UnexpectedErrorFault_Exception;

    /**
     * Returns access information relevant to the current user
     */
    @WebMethod
    @RequestWrapper(localName = "getAccessInfo", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.GetAccessInfo")
    @ResponseWrapper(localName = "getAccessInfoResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.GetAccessInfoResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.GetAccessInfoResult getAccessInfo()
;

    /**
     * Impersonate as a given user in the current organization using the Salesforce.com SOAP API
     */
    @WebMethod
    @RequestWrapper(localName = "impersonateUser", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ImpersonateUser")
    @ResponseWrapper(localName = "impersonateUserResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ImpersonateUserResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.ImpersonateUserResult> impersonateUser(

        @WebParam(name = "userIds", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> userIds
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Ack the receipt of changed records for this user
     */
    @WebMethod
    @RequestWrapper(localName = "ackSyncOfflineData", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.AckSyncOfflineData")
    @ResponseWrapper(localName = "ackSyncOfflineDataResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.AckSyncOfflineDataResponse")
    public void ackSyncOfflineData(

        @WebParam(name = "token", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String token,
        @WebParam(name = "syncStateId", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String syncStateId
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Create a current sharing access snapshot for this sObject type
     */
    @WebMethod
    @RequestWrapper(localName = "createSnapshot", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.CreateSnapshot")
    @ResponseWrapper(localName = "createSnapshotResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.CreateSnapshotResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.SnapshotResult createSnapshot(

        @WebParam(name = "sObject", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObject,
        @WebParam(name = "forceFullSnapshot", targetNamespace = "urn:partner.soap.sforce.com")
        boolean forceFullSnapshot
    ) throws UnexpectedErrorFault_Exception, InvalidQueryLocatorFault_Exception;

    /**
     * Merge and update a set of sObjects based on object id
     */
    @WebMethod
    @RequestWrapper(localName = "merge", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Merge")
    @ResponseWrapper(localName = "mergeResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.MergeResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.MergeResult> merge(

        @WebParam(name = "request", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.MergeRequest> request
    ) throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception, InvalidFieldFault_Exception;

    /**
     * Describe the views of an sObject
     */
    @WebMethod
    @RequestWrapper(localName = "describeListViews", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeListViews")
    @ResponseWrapper(localName = "describeListViewsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeListViewsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeListViewResult> describeListViews(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> sObjectType
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Make this snapshot the new baseline snapshot
     */
    @WebMethod
    @RequestWrapper(localName = "ackSnapshot", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.AckSnapshot")
    @ResponseWrapper(localName = "ackSnapshotResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.AckSnapshotResponse")
    public void ackSnapshot(

        @WebParam(name = "snapshotId", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String snapshotId
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Resumes a paused flow interview
     */
    @WebMethod
    @RequestWrapper(localName = "resumeFlowInterview", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ResumeFlowInterview")
    @ResponseWrapper(localName = "resumeFlowInterviewResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ResumeFlowInterviewResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.NavigateFlowInterviewResult resumeFlowInterview(

        @WebParam(name = "request", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.ResumeFlowInterviewRequest request
    );

    /**
     * Logout the current user, invalidating the current session.
     */
    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.LogoutResponse")
    public void logout()
 throws UnexpectedErrorFault_Exception;

    /**
     * Describe all tabs available to a user
     */
    @WebMethod
    @RequestWrapper(localName = "describeAllTabs", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeAllTabs")
    @ResponseWrapper(localName = "describeAllTabsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeAllTabsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeTab> describeAllTabs()
 throws UnexpectedErrorFault_Exception;

    /**
     * Describe the data category group structures for a given set of pair of types and data category group name
     */
    @WebMethod
    @RequestWrapper(localName = "describeDataCategoryGroupStructures", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeDataCategoryGroupStructures")
    @ResponseWrapper(localName = "describeDataCategoryGroupStructuresResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeDataCategoryGroupStructuresResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeDataCategoryGroupStructureResult> describeDataCategoryGroupStructures(

        @WebParam(name = "pairs", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.DataCategoryGroupSobjectTypePair> pairs,
        @WebParam(name = "topCategoriesOnly", targetNamespace = "urn:partner.soap.sforce.com")
        boolean topCategoriesOnly
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Match a set of sObjects with specified rule
     */
    @WebMethod
    @RequestWrapper(localName = "match", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Match")
    @ResponseWrapper(localName = "matchResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.MatchResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.MatchResult> match(

        @WebParam(name = "sObjects", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.SObject> sObjects,
        @WebParam(name = "matchOptions", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.MatchOptions matchOptions
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception, InvalidFieldFault_Exception;

    /**
     * Describe all the data category groups available for a given set of types
     */
    @WebMethod
    @RequestWrapper(localName = "describeDataCategoryGroups", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeDataCategoryGroups")
    @ResponseWrapper(localName = "describeDataCategoryGroupsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeDataCategoryGroupsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeDataCategoryGroupResult> describeDataCategoryGroups(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> sObjectType
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Submit an entity to a workflow process or process a workitem
     */
    @WebMethod
    @RequestWrapper(localName = "process", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ProcessResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.ProcessResult> process(

        @WebParam(name = "actions", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.ProcessRequest> actions
    ) throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception;

    /**
     * Describe the Global state
     */
    @WebMethod
    @RequestWrapper(localName = "describeGlobal", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeGlobal")
    @ResponseWrapper(localName = "describeGlobalResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeGlobalResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeGlobalResult describeGlobal()
 throws UnexpectedErrorFault_Exception;

    /**
     * Describe the primary compact layouts for the sObjects requested
     */
    @WebMethod
    @RequestWrapper(localName = "describePrimaryCompactLayouts", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribePrimaryCompactLayouts")
    @ResponseWrapper(localName = "describePrimaryCompactLayoutsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribePrimaryCompactLayoutsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeCompactLayout> describePrimaryCompactLayouts(

        @WebParam(name = "sObjectTypes", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> sObjectTypes
    );

    /**
     * Describe a list of entity names that reflects the current user's searchable entities
     */
    @WebMethod
    @RequestWrapper(localName = "describeSearchableEntities", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSearchableEntities")
    @ResponseWrapper(localName = "describeSearchableEntitiesResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSearchableEntitiesResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeSearchableEntityResult> describeSearchableEntities(

        @WebParam(name = "includeOnlyEntitiesWithTabs", targetNamespace = "urn:partner.soap.sforce.com")
        boolean includeOnlyEntitiesWithTabs
    );

    /**
     * Describe a Picklist field
     */
    @WebMethod
    @RequestWrapper(localName = "describePicklists", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribePicklists")
    @ResponseWrapper(localName = "describePicklistsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribePicklistsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribePicklistResult> describePicklists(

        @WebParam(name = "param", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.DescribePicklistsParam param
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception, InvalidFieldFault_Exception;

    /**
     * convert a set of leads
     */
    @WebMethod
    @RequestWrapper(localName = "convertLead", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ConvertLead")
    @ResponseWrapper(localName = "convertLeadResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ConvertLeadResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.LeadConvertResult> convertLead(

        @WebParam(name = "leadConverts", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.LeadConvert> leadConverts
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Describe the ListViews of a SObject as SOQL metadata for the generation of SOQL.
     */
    @WebMethod
    @RequestWrapper(localName = "describeSObjectListViews", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSObjectListViews")
    @ResponseWrapper(localName = "describeSObjectListViewsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSObjectListViewsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeSoqlListViewResult describeSObjectListViews(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType,
        @WebParam(name = "recentsOnly", targetNamespace = "urn:partner.soap.sforce.com")
        boolean recentsOnly,
        @WebParam(name = "isSoqlCompatible", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.ListViewIsSoqlCompatible isSoqlCompatible,
        @WebParam(name = "limit", targetNamespace = "urn:partner.soap.sforce.com")
        int limit,
        @WebParam(name = "offset", targetNamespace = "urn:partner.soap.sforce.com")
        int offset
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Delete a set of sObjects
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DeleteResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DeleteResult> delete(

        @WebParam(name = "ids", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> ids
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Starts a flow interview
     */
    @WebMethod
    @RequestWrapper(localName = "startFlowInterview", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.StartFlowInterview")
    @ResponseWrapper(localName = "startFlowInterviewResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.StartFlowInterviewResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.NavigateFlowInterviewResult startFlowInterview(

        @WebParam(name = "request", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.StartFlowInterviewRequest request
    );

    /**
     * Create a Query Cursor, including deleted sObjects
     */
    @WebMethod
    @RequestWrapper(localName = "queryAll", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.QueryAll")
    @ResponseWrapper(localName = "queryAllResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.QueryAllResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.QueryResult queryAll(

        @WebParam(name = "queryString", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String queryString
    ) throws MalformedQueryFault_Exception, InvalidIdFault_Exception, UnexpectedErrorFault_Exception, InvalidQueryLocatorFault_Exception, InvalidFieldFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Update a set of sObjects
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.UpdateResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.SaveResult> update(

        @WebParam(name = "sObjects", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.SObject> sObjects
    ) throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception, InvalidFieldFault_Exception;

    /**
     * Add or update campaign member
     */
    @WebMethod
    @RequestWrapper(localName = "addCampaignMember", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.AddCampaignMember")
    @ResponseWrapper(localName = "addCampaignMemberResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.AddCampaignMemberResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.AddCampaignMemberResult addCampaignMember(

        @WebParam(name = "AddCampaignMemberOptions", targetNamespace = "urn:partner.soap.sforce.com")
        com.sforce.partner.AddCampaignMemberOptions addCampaignMemberOptions
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception, InvalidFieldFault_Exception;

    /**
     * Empty a set of sObjects from the recycle bin
     */
    @WebMethod
    @RequestWrapper(localName = "emptyRecycleBin", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.EmptyRecycleBin")
    @ResponseWrapper(localName = "emptyRecycleBinResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.EmptyRecycleBinResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.EmptyRecycleBinResult> emptyRecycleBin(

        @WebParam(name = "ids", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> ids
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Get changed records for this user
     */
    @WebMethod
    @RequestWrapper(localName = "syncOfflineData", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.SyncOfflineData")
    @ResponseWrapper(localName = "syncOfflineDataResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.SyncOfflineDataResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.SyncOfflineDataResult syncOfflineData(

        @WebParam(name = "reset", targetNamespace = "urn:partner.soap.sforce.com")
        boolean reset,
        @WebParam(name = "userRequested", targetNamespace = "urn:partner.soap.sforce.com")
        boolean userRequested,
        @WebParam(name = "syncStateId", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String syncStateId,
        @WebParam(name = "syncFull", targetNamespace = "urn:partner.soap.sforce.com")
        boolean syncFull,
        @WebParam(name = "skipNewsFeeds", targetNamespace = "urn:partner.soap.sforce.com")
        boolean skipNewsFeeds,
        @WebParam(name = "idsToSpider", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> idsToSpider,
        @WebParam(name = "entitiesToSync", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> entitiesToSync
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Change the current user's password
     */
    @WebMethod
    @RequestWrapper(localName = "changeOwnPassword", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ChangeOwnPassword")
    @ResponseWrapper(localName = "changeOwnPasswordResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ChangeOwnPasswordResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.ChangeOwnPasswordResult changeOwnPassword(

        @WebParam(name = "oldPassword", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String oldPassword,
        @WebParam(name = "newPassword", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String newPassword
    ) throws InvalidOldPasswordFault_Exception, InvalidNewPasswordFault_Exception, UnexpectedErrorFault_Exception;

    /**
     * Describe the details of a series of quick actions available for the given contextType
     */
    @WebMethod
    @RequestWrapper(localName = "describeAvailableQuickActions", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeAvailableQuickActions")
    @ResponseWrapper(localName = "describeAvailableQuickActionsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeAvailableQuickActionsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeAvailableQuickActionResult> describeAvailableQuickActions(

        @WebParam(name = "contextType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String contextType
    );

    /**
     * Get the IDs for deleted sObjects
     */
    @WebMethod
    @RequestWrapper(localName = "getDeleted", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.GetDeleted")
    @ResponseWrapper(localName = "getDeletedResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.GetDeletedResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.GetDeletedResult getDeleted(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType,
        @WebParam(name = "startDate", targetNamespace = "urn:partner.soap.sforce.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "urn:partner.soap.sforce.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Retrieve the template sobjects, if appropriate, for the given quick action names in a given contexts when used a mass quick action
     */
    @WebMethod
    @RequestWrapper(localName = "retrieveMassQuickActionTemplates", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.RetrieveMassQuickActionTemplates")
    @ResponseWrapper(localName = "retrieveMassQuickActionTemplatesResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.RetrieveMassQuickActionTemplatesResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.QuickActionTemplateResult> retrieveMassQuickActionTemplates(

        @WebParam(name = "quickActionName", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String quickActionName,
        @WebParam(name = "contextIds", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> contextIds
    );

    /**
     * Send outbound email
     */
    @WebMethod
    @RequestWrapper(localName = "sendEmail", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.SendEmailResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.SendEmailResult> sendEmail(

        @WebParam(name = "messages", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.Email> messages
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Describe the DuplicateRule
     */
    @WebMethod
    @RequestWrapper(localName = "describeDuplicateRules", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeDuplicateRules")
    @ResponseWrapper(localName = "describeDuplicateRulesResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeDuplicateRulesResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeDuplicateRuleResult> describeDuplicateRules(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType
    ) throws UnexpectedErrorFault_Exception;

    /**
     * For testing purposes only
     */
    @WebMethod
    @RequestWrapper(localName = "ftestPatchPreviousVersion", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.FtestPatchPreviousVersion")
    @ResponseWrapper(localName = "ftestPatchPreviousVersionResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.FtestPatchPreviousVersionResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.SaveResult ftestPatchPreviousVersion()
;

    /**
     * Send existing draft EmailMessage
     */
    @WebMethod
    @RequestWrapper(localName = "sendEmailMessage", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.SendEmailMessage")
    @ResponseWrapper(localName = "sendEmailMessageResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.SendEmailMessageResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.SendEmailResult> sendEmailMessage(

        @WebParam(name = "ids", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> ids
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Describe a list of FlexiPage and their contents
     */
    @WebMethod
    @RequestWrapper(localName = "describeFlexiPages", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeFlexiPages")
    @ResponseWrapper(localName = "describeFlexiPagesResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeFlexiPagesResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeFlexiPageResult> describeFlexiPages(

        @WebParam(name = "flexiPages", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> flexiPages,
        @WebParam(name = "contexts", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.FlexipageContext> contexts
    ) throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception;

    /**
     * Create a Query Cursor
     */
    @WebMethod
    @RequestWrapper(localName = "query", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.QueryResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.QueryResult query(

        @WebParam(name = "queryString", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String queryString
    ) throws MalformedQueryFault_Exception, InvalidIdFault_Exception, UnexpectedErrorFault_Exception, InvalidQueryLocatorFault_Exception, InvalidFieldFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Perform a series of predefined actions such as quick create or log a task
     */
    @WebMethod
    @RequestWrapper(localName = "performQuickActions", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.PerformQuickActions")
    @ResponseWrapper(localName = "performQuickActionsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.PerformQuickActionsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.PerformQuickActionResult> performQuickActions(

        @WebParam(name = "quickActions", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.PerformQuickActionRequest> quickActions
    );

    /**
     * Undelete a set of sObjects
     */
    @WebMethod
    @RequestWrapper(localName = "undelete", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Undelete")
    @ResponseWrapper(localName = "undeleteResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.UndeleteResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.UndeleteResult> undelete(

        @WebParam(name = "ids", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> ids
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Get a set of sObjects
     */
    @WebMethod
    @RequestWrapper(localName = "retrieve", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Retrieve")
    @ResponseWrapper(localName = "retrieveResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.RetrieveResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.SObject> retrieve(

        @WebParam(name = "fieldList", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String fieldList,
        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType,
        @WebParam(name = "ids", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> ids
    ) throws MalformedQueryFault_Exception, InvalidIdFault_Exception, UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception, InvalidFieldFault_Exception;

    /**
     * Activate a set of sObjects
     */
    @WebMethod
    @RequestWrapper(localName = "activate", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Activate")
    @ResponseWrapper(localName = "activateResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ActivateResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.ActivateResult> activate(

        @WebParam(name = "ids", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> ids
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Return the renameable nouns from the server for use in presentation using the salesforce grammar engine
     */
    @WebMethod
    @RequestWrapper(localName = "describeNouns", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeNouns")
    @ResponseWrapper(localName = "describeNounsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeNounsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeNounResult> describeNouns(

        @WebParam(name = "nouns", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> nouns,
        @WebParam(name = "onlyRenamed", targetNamespace = "urn:partner.soap.sforce.com")
        boolean onlyRenamed,
        @WebParam(name = "includeFields", targetNamespace = "urn:partner.soap.sforce.com")
        boolean includeFields
    );

    /**
     * Find duplicates for a set of ids
     */
    @WebMethod
    @RequestWrapper(localName = "findDuplicatesByIds", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.FindDuplicatesByIds")
    @ResponseWrapper(localName = "findDuplicatesByIdsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.FindDuplicatesByIdsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.FindDuplicatesResult> findDuplicatesByIds(

        @WebParam(name = "ids", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> ids
    ) throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception;

    /**
     * Describe an sObject
     */
    @WebMethod
    @RequestWrapper(localName = "describeSObject", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSObject")
    @ResponseWrapper(localName = "describeSObjectResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSObjectResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeSObjectResult describeSObject(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String sObjectType
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Gets server timestamp
     */
    @WebMethod
    @RequestWrapper(localName = "getServerTimestamp", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.GetServerTimestamp")
    @ResponseWrapper(localName = "getServerTimestampResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.GetServerTimestampResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.GetServerTimestampResult getServerTimestamp()
 throws UnexpectedErrorFault_Exception;

    /**
     * Handle incoming email messages
     */
    @WebMethod
    @RequestWrapper(localName = "handleEmailMessage", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.HandleEmailMessage")
    @ResponseWrapper(localName = "handleEmailMessageResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.HandleEmailMessageResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.SaveResult> handleEmailMessage(

        @WebParam(name = "messages", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.HandledEmailMessage> messages
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Retrieve the template sobjects, if appropriate, for the given quick action names in a given context
     */
    @WebMethod
    @RequestWrapper(localName = "retrieveQuickActionTemplates", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.RetrieveQuickActionTemplates")
    @ResponseWrapper(localName = "retrieveQuickActionTemplatesResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.RetrieveQuickActionTemplatesResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.QuickActionTemplateResult> retrieveQuickActionTemplates(

        @WebParam(name = "quickActionNames", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> quickActionNames,
        @WebParam(name = "contextId", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String contextId
    );

    /**
     * Reset a user's password
     */
    @WebMethod
    @RequestWrapper(localName = "resetPassword", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ResetPassword")
    @ResponseWrapper(localName = "resetPasswordResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.ResetPasswordResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.ResetPasswordResult resetPassword(

        @WebParam(name = "userId", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.String userId
    ) throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception;

    /**
     * Describe the layout of the SoftPhone
     */
    @WebMethod
    @RequestWrapper(localName = "describeSoftphoneLayout", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSoftphoneLayout")
    @ResponseWrapper(localName = "describeSoftphoneLayoutResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSoftphoneLayoutResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public com.sforce.partner.DescribeSoftphoneLayoutResult describeSoftphoneLayout()
 throws UnexpectedErrorFault_Exception;

    /**
     * Create a set of new sObjects
     */
    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.CreateResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.SaveResult> create(

        @WebParam(name = "sObjects", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<com.sforce.partner.SObject> sObjects
    ) throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception, InvalidFieldFault_Exception;

    /**
     * Describe the search view of an sObject
     */
    @WebMethod
    @RequestWrapper(localName = "describeSearchLayouts", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSearchLayouts")
    @ResponseWrapper(localName = "describeSearchLayoutsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSearchLayoutsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeSearchLayoutResult> describeSearchLayouts(

        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> sObjectType
    ) throws UnexpectedErrorFault_Exception, InvalidSObjectFault_Exception;

    /**
     * Determine which actions are available for the given workitem
     */
    @WebMethod
    @RequestWrapper(localName = "describeWorkitemActions", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeWorkitemActions")
    @ResponseWrapper(localName = "describeWorkitemActionsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeWorkitemActionsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeWorkitemActionResult> describeWorkitemActions(

        @WebParam(name = "workitemIds", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> workitemIds
    ) throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception;

    /**
     * Logs out and invalidates session ids
     */
    @WebMethod
    @RequestWrapper(localName = "invalidateSessions", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.InvalidateSessions")
    @ResponseWrapper(localName = "invalidateSessionsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.InvalidateSessionsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.InvalidateSessionsResult> invalidateSessions(

        @WebParam(name = "sessionIds", targetNamespace = "urn:partner.soap.sforce.com")
        java.util.List<java.lang.String> sessionIds
    ) throws UnexpectedErrorFault_Exception;

    /**
     * Describe your Data Category Mappings.
     */
    @WebMethod
    @RequestWrapper(localName = "describeDataCategoryMappings", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeDataCategoryMappings")
    @ResponseWrapper(localName = "describeDataCategoryMappingsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeDataCategoryMappingsResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeDataCategoryMappingResult> describeDataCategoryMappings()
 throws UnexpectedErrorFault_Exception;

    /**
     * Describe a list of objects representing the order and scope of objects on a users search result page
     */
    @WebMethod
    @RequestWrapper(localName = "describeSearchScopeOrder", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSearchScopeOrder")
    @ResponseWrapper(localName = "describeSearchScopeOrderResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.sforce.partner.DescribeSearchScopeOrderResponse")
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    public java.util.List<com.sforce.partner.DescribeSearchScopeOrderResult> describeSearchScopeOrder(

        @WebParam(name = "includeRealTimeEntities", targetNamespace = "urn:partner.soap.sforce.com")
        java.lang.Boolean includeRealTimeEntities
    );
}
