package io.virtualan.services.helloworld;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-21T07:44:15.252-05:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://virtualan.io/services/helloworld", name = "HelloWorld_PortType")
@XmlSeeAlso({io.virtualan.types.helloworld.ObjectFactory.class})
public interface HelloWorldPortType {

    @WebMethod(action = "http://virtualan.io/services/helloworld/sayHello")
    @RequestWrapper(localName = "person", targetNamespace = "http://virtualan.io/types/helloworld", className = "io.virtualan.types.helloworld.Person")
    @ResponseWrapper(localName = "greeting", targetNamespace = "http://virtualan.io/types/helloworld", className = "io.virtualan.types.helloworld.Greeting")
    @WebResult(name = "greeting", targetNamespace = "http://virtualan.io/types/helloworld")
    public java.lang.String person(

        @WebParam(name = "firstName", targetNamespace = "http://virtualan.io/types/helloworld")
        java.lang.String firstName,
        @WebParam(name = "lastName", targetNamespace = "http://virtualan.io/types/helloworld")
        java.lang.String lastName
    );
}
