package io.virtualan.services.helloworld;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Hello World service
 *
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-21T07:44:15.257-05:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "HelloWorld_Service",
                  wsdlLocation = "file:/D:/Elan/virtualan-working-dir/service-vir/virtualan/samples/virtualan-wsdl-soap/src/main/resources/META-INF/resources/wsdl/Hello/helloworld.wsdl",
                  targetNamespace = "http://virtualan.io/services/helloworld")
public class HelloWorldService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://virtualan.io/services/helloworld", "HelloWorld_Service");
    public final static QName HelloWorldPort = new QName("http://virtualan.io/services/helloworld", "HelloWorld_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Elan/virtualan-working-dir/service-vir/virtualan/samples/virtualan-wsdl-soap/src/main/resources/META-INF/resources/wsdl/Hello/helloworld.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorldService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Elan/virtualan-working-dir/service-vir/virtualan/samples/virtualan-wsdl-soap/src/main/resources/META-INF/resources/wsdl/Hello/helloworld.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloWorldService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWorldService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloWorldPortType
     */
    @WebEndpoint(name = "HelloWorld_Port")
    public HelloWorldPortType getHelloWorldPort() {
        return super.getPort(HelloWorldPort, HelloWorldPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldPortType
     */
    @WebEndpoint(name = "HelloWorld_Port")
    public HelloWorldPortType getHelloWorldPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldPort, HelloWorldPortType.class, features);
    }

}
